version: '3'
services:
  kasm_agent:
    container_name: kasm_agent
    user: root
    image: "kasmweb/agent:1.13.1"
    read_only: true
    networks:
      - caddy
    volumes:
      - /opt/kasm/1.13.1:/opt/kasm/current
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/kasm/1.13.1/conf/nginx:/etc/nginx/conf.d
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  proxy:
    container_name: kasm_proxy
    image: "kasmweb/nginx:latest"
    ports:
      - "9443:9443"
    networks:
      - caddy
    volumes:
      - /opt/kasm/1.13.1/conf/nginx:/etc/nginx/conf.d:ro
      - /opt/kasm/1.13.1/certs/kasm_nginx.key:/etc/ssl/private/kasm_nginx.key
      - /opt/kasm/1.13.1/certs/kasm_nginx.crt:/etc/ssl/certs/kasm_nginx.crt
      - /opt/kasm/1.13.1/www:/srv/www:ro
      - /opt/kasm/1.13.1/log/nginx:/var/log/external/nginx/
      - /opt/kasm/1.13.1/log/logrotate:/var/log/external/logrotate/
    restart: always
    depends_on:
      - kasm_agent
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
networks:
  caddy:
    external: true
