version: "3.9"

services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - CF_API_TOKEN=4jk_MWfMLfNJPbJsZbpCw6WS_oR056lqJLvPzatp
      - DOMAINS=xfrc.xyz
      - PROXIED=false
