version: "3.9"

volumes:
  vaultwarden-data:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - vaultwarden-data:/opt/vaultwarden/data
    ports:
      - 8081:80
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - DOMAIN=${VW_DOMAIN}
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_DOMAINS_WHITELIST=${VW_DOMAIN}
    labels:
      # Services
      - "traefik.enable=true"
      - "traefik.http.services.vaultwarden-ui.loadbalancer.server.port=8081"
      - "traefik.http.services.vaultwarden-ws.loadbalancer.server.port=3012"
      # Webinterface HTTP (to HTTPS redirect)
      - "traefik.http.routers.vaultwarden.rule=Host(`${VW_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=http"
      - "traefik.http.routers.vaultwarden.service=vaultwarden-ui"
      - "traefik.http.routers.vaultwarden.middlewares=http-to-https@file"
      # Webinterface HTTPS
      - "traefik.http.routers.vaultwarden-ssl.rule=Host(`${VW_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden-ssl.entrypoints=https"
      - "traefik.http.routers.vaultwarden-ssl.service=vaultwarden-ui"
      - "traefik.http.routers.vaultwarden-ssl.tls=true"
      # Websocket HTTP (to HTTPS redirect)
      - "traefik.http.routers.vaultwarden-websocket.rule=Host(`${VW_DOMAIN}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket.entrypoints=http"
      - "traefik.http.routers.vaultwarden-websocket.service=vaultwarden-ws"
      - "traefik.http.routers.vaultwarden-websocket.middlewares=http-to-https@file"
      # Websocket HTTPS
      - "traefik.http.routers.vaultwarden-websocket-ssl.rule=Host(`${VW_DOMAIN}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket-ssl.entrypoints=https"
      - "traefik.http.routers.vaultwarden-websocket-ssl.service=vaultwarden-ws"
      - "traefik.http.routers.vaultwarden-websocket-ssl.tls=true"
