kasmguac:
  id: 4f7784cc-610e-40c8-8451-71bc8493f4f5
  port: 3000
  server_address: kasm_guac
  server_port: 9443
  zone: default
  
  kasm_delete_session_watch_interval: 60
  logging:
    errorEventName: error
    logDirectory: /opt/kasm/current/log/
    fileNamePattern: kasmguac-<DATE>.log
    dateFormat: YYYY.MM.DD
    timestampFormat: YYYY-MM-DD HH:mm:ss.SSS
api:
  hostnames: ['proxy','docker-box']
  port: 9443
  auth_token: SgtmLf5UjBhaoehUyVdkLk
  allow_self_signed_cert: true
  hostname_refresh_interval: 30
