version: "3.9"

networks:
  traefik-proxy:
    external: true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  nc-data:
    driver: local

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nc-data:/mnt/ncdata
    networks:
      - traefik-proxy
    ports:
      - 8080:8080

    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/mnt/ncdata

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    depends_on:
      - nextcloud
    networks:
      - traefik-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/azureuser/docker-box/aio/data/traefik.yml:/traefik.yml:ro
      - /home/azureuser/docker-box/aio/data/config.yml:/config.yml
      - /home/azureuser/docker-box/aio/data/letsencrypt:/letsencrypt
      - /home/azureuser/docker-box/aio/data/traefik.log:/traefik.log
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CF_API_EMAIL="agrivatedelbow@gmail.com"
      - CF_API_KEY=4124b9d3059b5b91d4ef9ae8dfae53e3831d5
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=xfrc.xyz
      - traefik.http.routers.traefik.tls.domains[0].sans=*.xfrc.xyz
      - traefik.http.routers.traefik.service=api@internal
